global:
  ingress:
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/tags: scos.delete.on.teardown=true
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"

elasticsearch:
  master:
    replicas: 2
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      name: data
      size: "10Gi"
      storageClass: "standard-ssd"

  data:
    replicas: 2
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      name: data
      size: "30Gi"
      storageClass: "standard-ssd"

kibana:
  replicas: 1
  ingress:
    enabled: true
    hosts: []
  service:
    internalPort: 5601
