apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: {{ .Release.Name }}
spec:
  type: filebeat
  version: 7.9.3
  elasticsearchRef:
    name: {{ .Release.Name }}
  config:
    filebeat.inputs:
    - type: container
      paths:
      - /var/log/containers/*.log
    filebeat.processors:
    - add_kubernetes_metadata:
        indexers:
        - container:
        - pod_name:    
        default_indexers.enabled: false
        host: ${NODE_NAME}
        matchers:
        - logs_path:
            logs_path: "/var/log/containers/"
    logging:
      level: info
    setup.ilm:
      enabled: true
      policy_file: /etc/filebeat/ilm-policy.json
      overwrite: true
      check_exists: false
  daemonSet:
    podTemplate:
      spec:
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        securityContext:
          runAsUser: 0
        serviceAccount: "{{ .Release.Name }}-filebeat"
        containers:
        - name: filebeat
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
          - name: etcfilebeat
            mountPath: /etc/filebeat
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: etcfilebeat
          configMap:
            name: "{{ .Release.Name }}-beats"
