apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-beats"
data:
  ilm-policy.json: |-
    {
      "policy": {
        "phases": {
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "1d"
              }
            }
          },
          "delete": {
            "min_age": "15d",
            "actions": {
              "delete": {} 
            }
          }
        }
      }
    }
