---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Release.Name }}-filebeat"
subjects:
- kind: ServiceAccount
  name: "{{ .Release.Name }}-filebeat"
roleRef:
  kind: ClusterRole
  name: "{{ .Release.Name }}-filebeat"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: "{{ .Release.Name }}-filebeat"
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-filebeat"
