apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "lexlogger.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.elasticsearch.client.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "lexlogger.elasticsearch.client.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "lexlogger.name" . }}
      component: {{ .Values.elasticsearch.client.name }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.elasticsearch.client.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "lexlogger.name" . }}
        component: {{ .Values.elasticsearch.client.name }}
        release: {{ .Release.Name }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/es-configmap.yaml") . | sha256sum }}
        {{- if .Values.elasticsearch.client.podAnnotations }}
{{ toYaml .Values.elasticsearch.client.podAnnotations | indent 8 }}
        {{- end }}
    spec:
{{- if .Values.elasticsearch.client.priorityClassName }}
      priorityClassName: "{{ .Values.elasticsearch.client.priorityClassName }}"
{{- end }}
      securityContext:
        fsGroup: 1000
      {{- if or .Values.elasticsearch.client.antiAffinity .Values.elasticsearch.client.nodeAffinity }}
      affinity:
      {{- end }}
      {{- if eq .Values.elasticsearch.client.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: {{ template "lexlogger.name" . }}
                  release: {{ .Release.Name }}
                  component: {{ .Values.elasticsearch.client.name }}
      {{- else if eq .Values.elasticsearch.client.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: {{ template "lexlogger.name" . }}
                  release: {{ .Release.Name }}
                  component: {{ .Values.elasticsearch.client.name }}
      {{- end }}
      {{- with .Values.elasticsearch.client.nodeAffinity }}
        nodeAffinity:
{{ toYaml . | indent 10 }}
      {{- end }}
{{- if .Values.elasticsearch.client.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.elasticsearch.client.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.elasticsearch.client.tolerations }}
      tolerations:
{{ toYaml .Values.elasticsearch.client.tolerations | indent 8 }}
{{- end }}
      initContainers:
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
      # and https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html#mlockall
      - name: "sysctl"
        image: "{{ .Values.elasticsearch.initImage.repository }}:{{ .Values.elasticsearch.initImage.tag }}"
        imagePullPolicy: {{ .Values.elasticsearch.initImage.pullPolicy | quote }}
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
{{- if .Values.elasticsearch.extraInitContainers }}
{{ tpl .Values.elasticsearch.extraInitContainers . | indent 6 }}
{{- end }}
      containers:
      - name: prometheus-es-exporter
        image: braedon/prometheus-es-exporter:0.5.1
        volumeMounts:
        - mountPath: /usr/src/app/exporter.cfg
          name: config
          subPath: exporter.cfg
        command: ["prometheus-es-exporter", "-p", "9206", "-e", "{{ template "lexlogger.elasticsearch.client.fullname" . }}:9200", "-c", "/usr/src/app/exporter.cfg"]
        ports:
        - containerPort: 9206
          name: es-metrics
      - name: elasticsearch
        env:
        - name: NODE_DATA
          value: "false"
        - name: NODE_MASTER
          value: "false"
        - name: DISCOVERY_SERVICE
          value: {{ template "lexlogger.fullname" . }}-discovery
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: ES_JAVA_OPTS
          value: "-Djava.net.preferIPv4Stack=true -Xms{{ .Values.elasticsearch.client.heapSize }} -Xmx{{ .Values.elasticsearch.client.heapSize }} {{ .Values.elasticsearch.cluster.additionalJavaOpts }}"
        {{- range $key, $value :=  .Values.elasticsearch.cluster.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        resources:
{{ toYaml .Values.elasticsearch.client.resources | indent 12 }}
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 90
        image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
        imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy | quote }}
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: config
          subPath: elasticsearch.yml
        - mountPath: /usr/share/elasticsearch/config/log4j2.properties
          name: config
          subPath: log4j2.properties
{{- if hasPrefix "2." .Values.elasticsearch.image.tag }}
        - mountPath: /usr/share/elasticsearch/config/logging.yml
          name: config
          subPath: logging.yml
{{- end }}
{{- if .Values.elasticsearch.cluster.keystoreSecret }}
        - name: keystore
          mountPath: "/usr/share/elasticsearch/config/elasticsearch.keystore"
          subPath: elasticsearch.keystore
          readOnly: true
{{- end }}
{{- if .Values.elasticsearch.image.pullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.elasticsearch.image.pullSecrets }}
        - name: {{ $pullSecret }}
      {{- end }}
{{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "lexlogger.fullname" . }}-elasticsearch
{{- if .Values.elasticsearch.cluster.keystoreSecret }}
      - name: keystore
        secret:
          secretName: {{ .Values.elasticsearch.cluster.keystoreSecret }}
{{- end }}
