apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Release.Name }}
spec:
  version: 7.9.3
  count: {{ .Values.kibana.replicas }}
  elasticsearchRef:
    name: {{ .Release.Name }}
