{{- if .Values.kibana.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
{{- if .Values.global.ingress.annotations }}
{{ toYaml .Values.global.ingress.annotations | trim | indent 4 }}
{{- end }}
{{- if .Values.kibana.ingress.annotations }}
{{ toYaml .Values.kibana.ingress.annotations | trim | indent 4 }}
{{- end }}
  name: "{{ .Release.Name }}-kb"
spec:
  backend:
    serviceName: "{{ .Release.Name }}-kb-http"
    servicePort: {{ .Values.kibana.service.internalPort }}
  rules:
  {{- range .Values.kibana.ingress.hosts }}
    {{- $url := splitList "/" . }}
    - host: {{ first $url }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: redirect
              servicePort: use-annotation
  {{- end -}}
  {{- if .Values.kibana.ingress.tls }}
  tls:
{{ toYaml .Values.kibana.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
