apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "lexlogger.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.elasticsearch.master.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "lexlogger.fullname" . }}-discovery
spec:
  clusterIP: None
  ports:
    - port: 9300
      targetPort: transport
  selector:
    app: {{ template "lexlogger.name" . }}
    component: {{ .Values.elasticsearch.master.name }}
    release: {{ .Release.Name }}