apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ template "lexlogger.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.elasticsearch.master.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "lexlogger.elasticsearch.master.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "lexlogger.name" . }}
      component: {{ .Values.elasticsearch.master.name }}
      release: {{ .Release.Name }}
  serviceName: {{ template "lexlogger.elasticsearch.master.fullname" . }}
  replicas: {{ .Values.elasticsearch.master.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "lexlogger.name" . }}
        component: {{ .Values.elasticsearch.master.name }}
        release: {{ .Release.Name }}
        {{- if .Values.elasticsearch.master.podAnnotations }}
      annotations:
{{ toYaml .Values.elasticsearch.master.podAnnotations | indent 8 }}
        {{- end }}
    spec:
{{- if .Values.elasticsearch.master.priorityClassName }}
      priorityClassName: "{{ .Values.elasticsearch.master.priorityClassName }}"
{{- end }}
      securityContext:
        fsGroup: 1000
      {{- if or .Values.elasticsearch.master.antiAffinity .Values.elasticsearch.master.nodeAffinity }}
      affinity:
      {{- end }}
      {{- if eq .Values.elasticsearch.master.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: {{ template "lexlogger.name" . }}
                  release: "{{ .Release.Name }}"
                  component: {{ .Values.elasticsearch.master.name }}
      {{- else if eq .Values.elasticsearch.master.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: {{ template "lexlogger.name" . }}
                  release: "{{ .Release.Name }}"
                  component: {{ .Values.elasticsearch.master.name }}
      {{- end }}
      {{- with .Values.elasticsearch.master.nodeAffinity }}
        nodeAffinity:
{{ toYaml . | indent 10 }}
      {{- end }}
{{- if .Values.elasticsearch.master.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.elasticsearch.master.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.elasticsearch.master.tolerations }}
      tolerations:
{{ toYaml .Values.elasticsearch.master.tolerations | indent 8 }}
{{- end }}
      initContainers:
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
      # and https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html#mlockall
      - name: "sysctl"
        image: "{{ .Values.elasticsearch.initImage.repository }}:{{ .Values.elasticsearch.initImage.tag }}"
        imagePullPolicy: {{ .Values.elasticsearch.initImage.pullPolicy | quote }}
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: "chown"
        image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
        imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy | quote }}
        command:
        - /bin/bash
        - -c
        - chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/data &&
          chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/logs
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
{{- if .Values.elasticsearch.extraInitContainers }}
{{ tpl .Values.elasticsearch.extraInitContainers . | indent 6 }}
{{- end }}
      containers:
      - name: elasticsearch
        env:
        - name: NODE_DATA
          value: "false"
        - name: DISCOVERY_SERVICE
          value: {{ template "lexlogger.fullname" . }}-discovery
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: ES_JAVA_OPTS
          value: "-Djava.net.preferIPv4Stack=true -Xms{{ .Values.elasticsearch.master.heapSize }} -Xmx{{ .Values.elasticsearch.master.heapSize }} {{ .Values.elasticsearch.cluster.additionalJavaOpts }}"
        {{- range $key, $value :=  .Values.elasticsearch.cluster.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        resources:
{{ toYaml .Values.elasticsearch.master.resources | indent 12 }}
        readinessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 5
        image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
        imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy | quote }}
        ports:
        - containerPort: 9300
          name: transport
{{ if .Values.elasticsearch.master.exposeHttp }}
        - containerPort: 9200
          name: http
{{ end }}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: config
          subPath: elasticsearch.yml
{{- if .Values.elasticsearch.cluster.keystoreSecret }}
        - name: keystore
          mountPath: "/usr/share/elasticsearch/config/elasticsearch.keystore"
          subPath: elasticsearch.keystore
          readOnly: true
{{- end }}
{{- if .Values.elasticsearch.image.pullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.elasticsearch.image.pullSecrets }}
        - name: {{ $pullSecret }}
      {{- end }}
{{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "lexlogger.fullname" . }}-elasticsearch
{{- if .Values.elasticsearch.cluster.keystoreSecret }}
      - name: keystore
        secret:
          secretName: {{ .Values.elasticsearch.cluster.keystoreSecret }}
{{- end }}
  {{- if not .Values.elasticsearch.master.persistence.enabled }}
      - name: data
        emptyDir: {}
  {{- end }}
  updateStrategy:
    type: {{ .Values.elasticsearch.master.updateStrategy.type }}
  {{- if .Values.elasticsearch.master.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.elasticsearch.master.persistence.name }}
    spec:
      accessModes:
        - {{ .Values.elasticsearch.master.persistence.accessMode | quote }}
    {{- if .Values.elasticsearch.master.persistence.storageClass }}
    {{- if (eq "-" .Values.elasticsearch.master.persistence.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.elasticsearch.master.persistence.storageClass }}"
    {{- end }}
    {{- end }}
      resources:
        requests:
          storage: "{{ .Values.elasticsearch.master.persistence.size }}"
  {{ end }}