apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "lexlogger.fluentbit.fullname" . }}
  labels:
    app: {{ template "lexlogger.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.fluentbit.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "lexlogger.name" . }}
      component: {{ .Values.fluentbit.name }}
      release: {{ .Release.Name }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "lexlogger.name" . }}
        component: {{ .Values.fluentbit.name }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/fluentbit-configmap.yaml") . | sha256sum }}
{{- if .Values.fluentbit.podAnnotations }}
{{ toYaml .Values.fluentbit.podAnnotations | indent 8 }}
{{- end }}
    spec:
{{- if .Values.fluentbit.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.fluentbit.image.pullSecrets | indent 8 }}
{{- end }}
      serviceAccountName: {{ template "lexlogger.serviceAccountName.fluentbit" . }}
      containers:
      - name: fluentbit
        image: "{{ .Values.fluentbit.image.repository }}:{{ .Values.fluentbit.image.tag }}"
        imagePullPolicy: "{{ .Values.fluentbit.image.pullPolicy }}"
        env:
{{ toYaml .Values.fluentbit.env | indent 10 }}
        resources:
{{ toYaml .Values.fluentbit.resources | indent 10 }}
{{- if .Values.fluentbit.metrics.enabled }}
        ports:
          - name: metrics
            containerPort: 2020
            protocol: TCP
{{- end }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit.conf
          subPath: fluent-bit.conf
{{- if .Values.fluentbit.parsers.enabled }}
        - name: config
          mountPath: /fluent-bit/etc/parsers_custom.conf
          subPath: parsers.conf
{{- end }}
{{- if .Values.fluentbit.trackOffsets }}
        - name: tail-db
          mountPath: /tail-db
{{- end }}
{{- if .Values.fluentbit.extraVolumeMounts }}
{{ toYaml .Values.fluentbit.extraVolumeMounts | indent 8 }}
{{- end }}
{{ if .Values.fluentbit.on_minikube }}
        - name: mnt
          mountPath: /mnt
          readOnly: true
{{ end }}
      terminationGracePeriodSeconds: 10
    {{- if .Values.fluentbit.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.fluentbit.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.fluentbit.tolerations }}
      tolerations:
{{ toYaml .Values.fluentbit.tolerations | indent 8 }}
    {{- end }}
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
{{- if .Values.fluentbit.trackOffsets }}
      - name: tail-db
        hostPath:
          path: /var/lib/fluent-bit
          type: DirectoryOrCreate
{{- end }}
      - name: config
        configMap:
          name: {{ if .Values.fluentbit.existingConfigMap }}{{ .Values.fluentbit.existingConfigMap }}{{- else }}{{ template "lexlogger.fluentbit.fullname" . }}-config{{- end }}
{{- if .Values.fluentbit.extraVolumes }}
{{ toYaml .Values.fluentbit.extraVolumes | indent 6 }}
{{- end }}
{{ if .Values.fluentbit.on_minikube }}
      - name: mnt
        hostPath:
          path: /mnt
{{ end }}