apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lexlogger.fluentd.fullname" . }}-config
  labels:
    app: {{ template "lexlogger.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.fluentd.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.fluentd.configMaps }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}