{{- if (empty .Values.fluentbit.existingConfigMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "logstack.fluentbit.fullname" . }}-config
  labels:
    app: {{ template "logstack.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
{{- if .Values.fluentbit.parsers.enabled }}
        Parsers_File parsers_custom.conf
{{- end }}
{{- if .Values.fluentbit.metrics.enabled }}
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020
{{- end }}

    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Parser           docker
        Tag              {{ .Values.fluentbit.filter.kubeTag }}.*
        Refresh_Interval 5
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
{{- if .Values.fluentbit.trackOffsets }}
        DB               /tail-db/tail-containers-state.db
        DB.Sync          Normal
{{- end }}

    [FILTER]
        Name                kubernetes
        Match               {{ .Values.fluentbit.filter.kubeTag }}.*
        Kube_URL            {{ .Values.fluentbit.filter.kubeURL }}
        Kube_CA_File        {{ .Values.fluentbit.filter.kubeCAFile }}
        Kube_Token_File     {{ .Values.fluentbit.filter.kubeTokenFile }}
{{- if .Values.fluentbit.filter.mergeJSONLog }}
        Merge_JSON_Log      On
{{- end }}
{{- if .Values.fluentbit.filter.enableParser }}
        K8S-Logging.Parser  On
{{- end }}
{{- if .Values.fluentbit.filter.enableExclude }}
        K8S-Logging.Exclude On
{{- end }}
    [OUTPUT]
        Name          forward
        Match         *
        Host          {{ .Values.fluentbit.backend.forward.host }}
        Port          {{ .Values.fluentbit.backend.forward.port }}
        Retry_Limit False

  parsers.conf: |-
{{- if .Values.fluentbit.parsers.regex }}
{{- range .Values.fluentbit.parsers.regex }}
    [PARSER]
        Name        {{ .name }}
        Format      regex
        Regex       {{ .regex }}
{{- if .timeKey }}
        Time_Key    {{ .timeKey }}
{{- end }}
{{- if .timeFormat }}
        Time_Format {{ .timeFormat }}
{{- end }}
{{ end }}
{{- end }}
{{- if .Values.fluentbit.parsers.json }}
{{- range .Values.fluentbit.parsers.json }}
    [PARSER]
        Name        {{ .name }}
        Format      json
{{- if .timeKeep }}
        Time_Keep    {{ .timeKeep }}
{{- end }}
{{- if .timeKey }}
        Time_Key    {{ .timeKey }}
{{- end }}
{{- if .timeFormat }}
        Time_Format {{ .timeFormat }}
{{- end }}
{{- if .decodeFieldAs  }}
        Decode_Field_As {{ .decodeFieldAs }} {{ .decodeField | default "log" }}
{{- end }}
{{ end }}
{{- end }}

{{- end -}}