apiVersion: v1
kind: Service
metadata:
  name: {{ template "logstack.fluentd.fullname" . }}
  labels:
    app: {{ template "logstack.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.fluentd.service.type }}
  ports:
  {{- range $port := .Values.fluentd.service.ports }}
    - name: {{ $port.name }}
      port: {{ $port.containerPort }}
      targetPort: {{ $port.containerPort }}
      protocol: {{ $port.protocol }}
  {{- end }}
  selector:
    component: "{{ .Values.fluentd.name }}"
    release: {{ .Release.Name }}