{{- if .Values.fluentbit.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "logstack.fluentbit.fullname" . }}-metrics
  labels:
    app: {{ template "logstack.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.fluentbit.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.fluentbit.metrics.service.type}}
  sessionAffinity: None
  ports:
  - port: {{ .Values.fluentbit.metrics.service.port }}
    targetPort: metrics
    name: metrics
  selector:
    component: {{ .Values.fluentbit.name }}
    release: {{ .Release.Name }}
{{- end }}