apiVersion: v1
kind: Service
metadata:
  name: {{ template "lexlogger.fluentd.fullname" . }}
  labels:
    app: {{ template "lexlogger.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.fluentd.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    prometheus.io/port: "24231"
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.fluentd.service.type }}
  ports:
  {{- range $port := .Values.fluentd.service.ports }}
    - name: {{ $port.name }}
      port: {{ $port.containerPort }}
      targetPort: {{ $port.containerPort }}
      protocol: {{ $port.protocol }}
  {{- end }}
  selector:
    component: {{ .Values.fluentd.name }}
    release: {{ .Release.Name }}
