{{- if .Values.serviceAccounts.fluentbit.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "logstack.name" . }}
    component: "{{ .Values.fluentbit.name }}"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "logstack.serviceAccountName.fluentbit" . }}
{{- end -}}