apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "logstack.kibana.fullname" . }}
  labels:
    app: {{ template "logstack.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.kibana.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.kibana.files }}
  {{ $key }}: |
{{ toYaml $value | default "{}" | indent 4 }}
{{- end -}}