{{- if .Values.serviceAccounts.kibana.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "logstack.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.kibana.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "logstack.serviceAccountName.kibana" . }}
{{- end -}}