apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "logstack.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.kibana.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- range $key, $value := .Values.kibana.service.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  name: {{ template "logstack.kibana.fullname" . }}
  annotations:
    {{- range $key, $value := .Values.kibana.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.kibana.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range $cidr := .Values.kibana.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
    {{- end }}
  {{- end }}
  type: {{ .Values.kibana.service.type }}
  ports:
    - port: {{ .Values.kibana.service.externalPort }}
{{- if not .Values.kibana.authProxyEnabled }}
      targetPort: {{ .Values.kibana.service.internalPort }}
{{- else }}
      targetPort: {{ .Values.kibana.service.authProxyPort }}
{{- end }}
      protocol: TCP
{{ if (and (eq .Values.kibana.service.type "NodePort") (not (empty .Values.kibana.service.nodePort))) }}
      nodePort: {{ .Values.kibana.service.nodePort }}
{{ end }}      
{{- if .Values.kibana.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.kibana.service.externalIPs | indent 4 }}
{{- end }}
  selector:
    app: {{ template "logstack.name" . }}
    component: {{ .Values.kibana.name }}
    release: {{ .Release.Name }}
{{- if .Values.kibana.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.kibana.service.loadBalancerIP }}
{{- end }}