{{- if .Values.serviceAccounts.kibana.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "lexlogger.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.kibana.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "lexlogger.serviceAccountName.kibana" . }}
{{- end -}}